# Generated by Django 3.1.4 on 2021-04-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('resume', models.TextField(verbose_name='Resumo')),
                ('conclusion', models.TextField(verbose_name='Conclusão')),
                ('image', models.FilePathField(path='/home/core/static/img/games/', verbose_name='Imagem')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('graphics', models.FloatField(verbose_name='Gráficos')),
                ('optimization', models.FloatField(verbose_name='Otimização')),
                ('gameplay', models.FloatField(verbose_name='Gameplay')),
                ('difficulty', models.FloatField(verbose_name='Dificuldade')),
                ('authorComment', models.CharField(max_length=50, verbose_name='Autor do Comentario')),
                ('comment', models.CharField(max_length=500, verbose_name='Comentario')),
                ('author', models.CharField(max_length=50, verbose_name='Autor do Post')),
                ('Aboutauthor', models.CharField(max_length=500, verbose_name='Sobre autor do Post')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('slug', models.SlugField(editable=False, verbose_name='URL')),
            ],
        ),
    ]
