# Generated by Django 3.1.4 on 2021-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210429_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='./../static/img/blog/', verbose_name='Imagem'),
        ),
    ]
