# Generated by Django 3.1.4 on 2021-11-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211118_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=200, verbose_name='Link da Imagem'),
        ),
    ]
